import Footer from "../components/Footer";
import Layout from "../components/Layout";
import Navbar from "../components/navbar";
import PageButton from "../components/pageButton";
import "../styles/globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Layout>
        <Navbar/>
        <PageButton/>
        {children}
        <Footer/>
        </Layout></body>
    </html>
  )
}
